using System;
using System.Threading.Tasks;
using System.Windows.Input;
using AnnoDesigner.Core.Controls;
using AnnoDesigner.Core.Extensions;
using AnnoDesigner.Core.Models;
using AnnoDesigner.Core.Services;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using AnnoDesigner.Helper;
using System.Collections.Specialized;
using AnnoDesigner.Models;
using AnnoDesigner.Models.Interface;

namespace AnnoDesigner.ViewModels
{
    public partial class ManageKeybindingsViewModel : ObservableObject
    {
        /// <summary>
        /// These keys match values in the Localization dictionary
        /// </summary>
        private const string EDIT = "Edit";
        private const string RECORDING = "Recording";
        private const string RESET_ALL = "ResetAll";
        private const string RESET_ALL_CONFIRMATION_MESSAGE = "ResetAllConfirmationMessage";

        private readonly ICommons commons;
        private readonly IMessageBoxService _messageBoxService;
        private readonly ILocalizationHelper _localizationHelper;
        [ObservableProperty]
        private HotkeyCommandManager hotkeyCommandManager;

        [ObservableProperty]
        private string editButtonText = EDIT;

        public ManageKeybindingsViewModel(HotkeyCommandManager hotkeyCommandManager,
            ICommons commons,
            IMessageBoxService messageBoxServiceToUse,
            ILocalizationHelper localizationHelperToUse)
        {
            HotkeyCommandManager = hotkeyCommandManager;
            _messageBoxService = messageBoxServiceToUse;
            _localizationHelper = localizationHelperToUse;
            this.commons = commons;
            this.commons.SelectedLanguageChanged += Instance_SelectedLanguageChanged;

            // Initialize per-hotkey edit button text
            InitializeHotkeyButtonTexts();
            // Watch for hotkeys being added later
            HotkeyCommandManager.CollectionChanged += HotkeyCommandManager_CollectionChanged;
        }

        private void Instance_SelectedLanguageChanged(object sender, EventArgs e)
        {
            UpdateRebindButtonText();
            // Update per-hotkey edit button labels to new language
            InitializeHotkeyButtonTexts();
        }

        // HotkeyCommandManager property is generated by the [ObservableProperty] attribute for 'manager'.

        [ObservableProperty]
        private string editButtonCurrentTextKey = EDIT;

        [RelayCommand]
        private void Edit(Hotkey hotkey)
        {
            // Set per-row recording indicator
            hotkey.EditButtonText = _localizationHelper.GetLocalization(RECORDING);

            var window = new HotkeyRecorderWindow() { Owner = App.Current.MainWindow };

            (Key key, ModifierKeys modifiers, ExtendedMouseAction action, ActionRecorder.ActionType actionType, bool userCancelled) = window.RecordNewAction();

            //Only set new hotkeys if the user didn't click cancel, and they didn't close the window without a key/action bound
            if (!userCancelled && !(key == Key.None && action == ExtendedMouseAction.None))
            {
                hotkey.UpdateHotkey(key, action, modifiers, actionType == ActionRecorder.ActionType.KeyAction ? GestureType.KeyGesture : GestureType.MouseGesture);
            }

            // Reset per-row text back to Edit
            hotkey.EditButtonText = _localizationHelper.GetLocalization(EDIT);
        }

        [RelayCommand]
        private async Task ResetHotkeys()
        {
            if (await _messageBoxService.ShowQuestion(_localizationHelper.GetLocalization(RESET_ALL_CONFIRMATION_MESSAGE),
                _localizationHelper.GetLocalization(RESET_ALL)).ConfigureAwait(false))
            {
                HotkeyCommandManager.ResetHotkeys();
            }
        }

        private void UpdateRebindButtonText()
        {
            EditButtonText = _localizationHelper.GetLocalization(EditButtonCurrentTextKey);
        }

        private void InitializeHotkeyButtonTexts()
        {
            if (HotkeyCommandManager?.ObservableCollection is null)
            {
                return;
            }
            
            var EDIT_LOCALIZED = _localizationHelper.GetLocalization(EDIT);
            foreach (var hotkey in HotkeyCommandManager.ObservableCollection)
            {
                hotkey.EditButtonText = EDIT_LOCALIZED;
            }
        }

        private void HotkeyCommandManager_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems is null)
            {
                return;
            }

            var EDIT_LOCALIZED = _localizationHelper.GetLocalization(EDIT);
            foreach (var item in e.NewItems)
            {
                if (item is Hotkey hotkey)
                {
                    hotkey.EditButtonText = EDIT_LOCALIZED;
                }
            }
        }
    }
}
