using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Windows.Input;
using System.Windows.Navigation;
using AnnoDesigner.Core.Models;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using AnnoDesigner.Models;

namespace AnnoDesigner.ViewModels
{
    public partial class PreferencesViewModel : ObservableObject
    {
        private PreferencePage _selectedItem;

        [ObservableProperty]
        private ObservableCollection<PreferencePage> _pages = new();

        public PreferencesViewModel()
        {
            // Pages collection is initialised by the generated backing field
        }

        public NavigationService NavigationService { get; set; }

        public PreferencePage SelectedItem
        {
            get => _selectedItem;
            set
            {
                if (SetProperty(ref _selectedItem, value) && value != null)
                {
                    ShowPage(value.Name);
                }
            }
        }

        // Pages property is generated by the [ObservableProperty] attribute

        public void ShowFirstPage()
        {
            SelectedItem = Pages.First();
        }

        private void ShowPage(string name)
        {
            var foundPage = Pages.SingleOrDefault(x => x.Name.Equals(name, StringComparison.OrdinalIgnoreCase));
            if (foundPage != null)
            {
                NavigationService?.Navigate(new Uri($@"pack://application:,,,/Views\PreferencesPages\{name}.xaml", UriKind.RelativeOrAbsolute), foundPage.ViewModel);
            }
#if DEBUG
            else
            {
                throw new KeyNotFoundException($"Page {name}.xaml not found.");
            }
#endif
        }

        [RelayCommand]
        private void CloseWindow(ICloseable? window)
        {
            window?.Close();
        }
    }
}
