#nullable enable

using System;
using System.Collections.ObjectModel;
using System.Linq;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using System.Windows.Controls;
using System.Windows.Input;
using AnnoDesigner.Core.Models;
using AnnoDesigner.Models;
using AnnoDesigner.Models.Interface;
using static AnnoDesigner.Core.CoreConstants;
using System.Diagnostics;

namespace AnnoDesigner.ViewModels
{
    public partial class PresetsTreeSearchViewModel : ObservableObject
    {
        [ObservableProperty]
        private string _searchText = string.Empty;

        [ObservableProperty]
        private bool _hasFocus;

        [ObservableProperty]
        private ObservableCollection<GameVersionFilter> _gameVersionFilters = new();

        // internal flag used when updating the GameVersionFilters programmatically
        private bool _isUpdatingGameVersionFilter;

        public PresetsTreeSearchViewModel()
        {
            HasFocus = false;
            // GameVersionFilters already initialised by the generated backing-field
            SuggestionsList = new ObservableCollection<string>();
            InitGameVersionFilters();
        }

        // Debounced output value - exposed so other parts of the app (MainViewModel) can act
        // on a stabilized search string instead of every keystroke
        private string _debouncedSearchText = string.Empty;
        public string DebouncedSearchText
        {
            get => _debouncedSearchText;
            private set
            {
                if (_debouncedSearchText != value)
                {
                    _debouncedSearchText = value;
                    OnPropertyChanged(nameof(DebouncedSearchText));
                }
            }
        }

        // Debounce implementation
        private System.Threading.CancellationTokenSource? _debounceCts;
        private const int DefaultDebounceDelayMs = 300; // Adjust as needed

        partial void OnSearchTextChanged(string value)
        {
            // Logging for diagnostics
            System.Diagnostics.Debug.WriteLine($"DEBUG: SearchText changed to: '{value}'");
            System.Console.WriteLine($"DEBUG: SearchText changed to: '{value}'");

            // Kick off debounce processing (non-blocking)
            _ = DebounceUpdateAsync(value);
        }

        private async System.Threading.Tasks.Task DebounceUpdateAsync(string value)
        {
            try
            {
                _debounceCts?.Cancel();
                _debounceCts?.Dispose();
                _debounceCts = new System.Threading.CancellationTokenSource();

                var ct = _debounceCts.Token;

                // Wait for the debounce interval - will be cancelled if new input arrives
                await System.Threading.Tasks.Task.Delay(DefaultDebounceDelayMs, ct).ConfigureAwait(false);

                // Apply the debounced value on the UI thread context
                // Use OnPropertyChanged from this object to notify bindings
                DebouncedSearchText = value;
            }
            catch (System.OperationCanceledException)
            {
                // expected when new input arrives
            }
            catch (Exception ex)
            {
                System.Diagnostics.Debug.WriteLine($"Debounce error: {ex.Message}");
            }
        }

        private void InitGameVersionFilters()
        {
            UnsubscribeFromFilterChanges();

            var order = 0;
            foreach (var curGameVersion in Enum.GetValues<GameVersion>())
            {
                if (curGameVersion is GameVersion.Unknown or GameVersion.All)
                {
                    continue;
                }

                var newFilter = new GameVersionFilter
                {
                    Name = curGameVersion.ToString().Replace("Anno", "Anno ", StringComparison.Ordinal),
                    Type = curGameVersion,
                    Order = ++order
                };

                // Subscribe to the change event so we can notify bindings for the derived SelectedGameVersionFilters property
                newFilter.FilterStateChanged += OnFilterItemStateChanged;

                GameVersionFilters.Add(newFilter);
            }
        }

        private void UnsubscribeFromFilterChanges()
        {
            foreach (var filter in GameVersionFilters)
            {
                filter.FilterStateChanged -= OnFilterItemStateChanged;
            }
        }

        private void OnFilterItemStateChanged(object? sender, EventArgs e)
        {
            if (_isUpdatingGameVersionFilter)
            {
                return;
            }

            // Notify the binding system that the derived property has changed.
            OnPropertyChanged(nameof(SelectedGameVersionFilters));
        }

        // SearchText backing field is generated by [ObservableProperty] above

        // HasFocus backing field is generated by [ObservableProperty] above

        // GameVersionFilters backing field is generated by [ObservableProperty] above

        public ObservableCollection<GameVersionFilter> SelectedGameVersionFilters => new ObservableCollection<GameVersionFilter>(GameVersionFilters.Where(x => x.IsSelected));

        public GameVersion SelectedGameVersions
        {
            get
            {
                var result = GameVersion.Unknown;
                foreach (var filter in GameVersionFilters.Where(x => x.IsSelected))
                {
                    result |= filter.Type;
                }
                return result;
            }
            set
            {
                try
                {
                    _isUpdatingGameVersionFilter = true;

                    foreach (var curFilter in GameVersionFilters)
                    {
                        curFilter.IsSelected = value.HasFlag(curFilter.Type);
                    }
                }
                finally
                {
                    _isUpdatingGameVersionFilter = false;

                    OnPropertyChanged(nameof(SelectedGameVersionFilters));
                }
            }
        }

        #region commands

        //TODO: refactor to use interface ICanUpdateLayout -> currently TextBox does not implement it (create own control?)
        [RelayCommand]
        private void ClearSearchText(object? param)
        {
            SearchText = string.Empty;

            if (param is ICanUpdateLayout updateable)
            {
                updateable.UpdateLayout();
            }
            else if (param is TextBox textBox)
            {
                Debug.WriteLine($"+ IsFocused: {textBox.IsFocused} | IsKeyboardFocused: {textBox.IsKeyboardFocused} | IsKeyboardFocusWithin: {textBox.IsKeyboardFocusWithin} | CaretIndex: {textBox.CaretIndex}");

                SearchText = string.Empty;

                Debug.WriteLine($"++ IsFocused: {textBox.IsFocused} | IsKeyboardFocused: {textBox.IsKeyboardFocused} | IsKeyboardFocusWithin: {textBox.IsKeyboardFocusWithin} | CaretIndex: {textBox.CaretIndex}");

                _ = textBox.Focus();
                textBox.UpdateLayout();

                Debug.WriteLine($"+++ IsFocused: {textBox.IsFocused} | IsKeyboardFocused: {textBox.IsKeyboardFocused} | IsKeyboardFocusWithin: {textBox.IsKeyboardFocusWithin} | CaretIndex: {textBox.CaretIndex}");
            }
        }
        [RelayCommand]
        private void ClearGameVersionFilter(object? param)
        {
            try
            {
                _isUpdatingGameVersionFilter = true;

                // Set IsSelected to false for every filter item
                foreach (var filter in GameVersionFilters)
                {
                    filter.IsSelected = false;
                }
            }
            finally
            {
                _isUpdatingGameVersionFilter = false;
                // Notify the application that the selected filters have changed
                OnPropertyChanged(nameof(SelectedGameVersionFilters));
            }
        }

        [RelayCommand]
        private void GotFocus(object? param)
        {
            HasFocus = true;
        }
        [RelayCommand]
        private void LostFocus(object? param)
        {
            HasFocus = false;
        }


        #endregion

        [ObservableProperty]
        private ObservableCollection<string> _suggestionsList = new();

    }
}
