using System;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Input;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using AnnoDesigner.CommandLine.Arguments;
using AnnoDesigner.Core.Extensions;
using AnnoDesigner.Core.Models;
using AnnoDesigner.Core.Services;
using AnnoDesigner.Models;
using AnnoDesigner.Models.Interface;
using NLog;

namespace AnnoDesigner.ViewModels
{
    public partial class UpdateSettingsViewModel : ObservableObject
    {
        private static readonly Logger logger = LogManager.GetCurrentClassLogger();

        private readonly ICommons _commons;
        private readonly IAppSettings _appSettings;
        private readonly IMessageBoxService _messageBoxService;
        private readonly IUpdateHelper _updateHelper;
        private readonly ILocalizationHelper _localizationHelper;

        // backing fields are generated by the source generator for [ObservableProperty]

        public UpdateSettingsViewModel(ICommons commonsToUse,
            IAppSettings appSettingsToUse,
            IMessageBoxService messageBoxServiceToUse,
            IUpdateHelper updateHelperToUse,
            ILocalizationHelper localizationHelperToUse)
        {
            _commons = commonsToUse;
            _appSettings = appSettingsToUse;
            _messageBoxService = messageBoxServiceToUse;
            _updateHelper = updateHelperToUse;
            _localizationHelper = localizationHelperToUse;

            // Commands are generated via [RelayCommand] attributes.
        }

        private AvailableRelease FoundPresetRelease { get; set; }

        public async Task CheckForUpdates(bool isAutomaticUpdateCheck)
        {
            try
            {
                IsUpdateError = false;
                IsAppUpToDate = false;
                IsUpdateAvailable = false;
                IsPresetUpdateAvailable = false;

                BusyContent = _localizationHelper.GetLocalization("UpdatePreferencesBusyCheckUpdates");
                IsBusy = true;

                await CheckForNewAppVersionAsync();

                await CheckForPresetsAsync(isAutomaticUpdateCheck);

                if (!isAutomaticUpdateCheck)
                {
                    IsAppUpToDate = !IsUpdateAvailable && !IsPresetUpdateAvailable;
                }

                if (isAutomaticUpdateCheck)
                {
                    //If not already prompted
                    if (!_appSettings.PromptedForAutoUpdateCheck)
                    {
                        _appSettings.PromptedForAutoUpdateCheck = true;

                        if (!await _messageBoxService.ShowQuestion(Application.Current.MainWindow,
                            _localizationHelper.GetLocalization("ContinueCheckingForUpdates"),
                            _localizationHelper.GetLocalization("ContinueCheckingForUpdatesTitle")))
                        {
                            AutomaticUpdateCheck = false;
                        }
                    }
                }

                IsBusy = false;
            }
            catch (Exception ex)
            {
                logger.Error(ex, "Error checking version.");

                IsUpdateError = true;

                IsBusy = false;

                if (isAutomaticUpdateCheck)
                {
                    _messageBoxService.ShowError(Application.Current.MainWindow,
                        _localizationHelper.GetLocalization("VersionCheckErrorMessage"),
                        _localizationHelper.GetLocalization("VersionCheckErrorTitle"));
                }
            }
        }

        private async Task CheckForNewAppVersionAsync()
        {
            (var isNewAppVersionAvailable, var newAppVersion) = await _updateHelper.IsNewAppVersionAvailableAsync();

            if (isNewAppVersionAvailable)
            {
                UpdatedVersionValue = newAppVersion.ToString();
                IsUpdateAvailable = true;
                _messageBoxService.ShowMessage(Application.Current.MainWindow,
                    _localizationHelper.GetLocalization("UpdatePreferencesNewAppUpdateAvailable") + Environment.NewLine + Environment.NewLine + "https://github.com/AnnoDesigner/anno-designer/releases/",
                    _localizationHelper.GetLocalization("UpdatePreferencesUpdates"));
            }
            else
            {
                IsUpdateAvailable = false;
            }
        }

        private async Task CheckForPresetsAsync(bool isAutomaticUpdateCheck)
        {
            FoundPresetRelease = null;

            var foundRelease = await _updateHelper.GetAvailableReleasesAsync(ReleaseType.Presets);
            if (foundRelease == null)
            {
                return;
            }

            var isNewReleaseAvailable = foundRelease.Version > new Version(PresetsVersionValue);
            if (isNewReleaseAvailable)
            {
                IsPresetUpdateAvailable = true;
                FoundPresetRelease = foundRelease;

                if (isAutomaticUpdateCheck)
                {
                    if (await _messageBoxService.ShowQuestion(Application.Current.MainWindow,
                        _localizationHelper.GetLocalization("UpdateAvailablePresetMessage"),
                        _localizationHelper.GetLocalization("UpdateAvailableHeader")))
                    {
                        await DownloadPresetsAsync().ConfigureAwait(true);
                    }
                }
            }
        }

        [RelayCommand]
        private async Task CheckForUpdatesAsync()
        {
            await CheckForUpdates(isAutomaticUpdateCheck: false);
        }

        [RelayCommand]
        private void OpenReleases()
        {
            _ = Process.Start("https://github.com/AnnoDesigner/anno-designer/releases");
        }

        [RelayCommand]
        private async Task DownloadPresetsAsync()
        {
            if (FoundPresetRelease is null)
            {
                return;
            }

            BusyContent = _localizationHelper.GetLocalization("UpdatePreferencesBusyDownloadPresets");
            IsBusy = true;

            if (!_commons.CanWriteInFolder())
            {
                //already asked for admin rights?
                if (App.StartupArguments is AdminRestartArgs)
                {
                    _messageBoxService.ShowWarning($"You have no write access to the folder.{Environment.NewLine}The update can not be installed.",
                        _localizationHelper.GetLocalization("Error"));

                    IsBusy = false;
                    return;
                }

                _messageBoxService.ShowMessage(_localizationHelper.GetLocalization("UpdateRequiresAdminRightsMessage"),
                    _localizationHelper.GetLocalization("AdminRightsRequired"));

                _appSettings.Save();
                _commons.RestartApplication(true, AdminRestartArgs.Arguments, App.ExecutablePath);
            }

            //Context is required here, do not use ConfigureAwait(false)
            var newLocation = await _updateHelper.DownloadReleaseAsync(FoundPresetRelease);
            logger.Debug($"downloaded new preset ({FoundPresetRelease.Version}): {newLocation}");

            IsBusy = false;

            _appSettings.Save();
            _commons.RestartApplication(false, null, App.ExecutablePath);

            Environment.Exit(-1);
        }

        [ObservableProperty]
        private bool automaticUpdateCheck;

        partial void OnAutomaticUpdateCheckChanged(bool value)
        {
            _appSettings.Save();
        }

        [ObservableProperty]
        private string versionValue;

        [ObservableProperty]
        private string fileVersionValue;

        [ObservableProperty]
        private string presetsVersionValue;

        [ObservableProperty]
        private bool updateSupportsPrerelease;

        partial void OnUpdateSupportsPrereleaseChanged(bool value)
        {
            _appSettings.Save();
        }

        [ObservableProperty]
        private bool showMultipleInstanceWarning;

        partial void OnShowMultipleInstanceWarningChanged(bool value)
        {
            _appSettings.Save();
        }

        [ObservableProperty]
        private bool isUpdateAvailable;

        [ObservableProperty]
        private bool isPresetUpdateAvailable;

        [ObservableProperty]
        private bool isAppUpToDate;

        [ObservableProperty]
        private bool isUpdateError;

        [ObservableProperty]
        private bool isBusy;

        [ObservableProperty]
        private string busyContent;

        [ObservableProperty]
        private string colorPresetsVersionValue;

        [ObservableProperty]
        private string treeLocalizationVersionValue;

        [ObservableProperty]
        private string updatedVersionValue;
    }
}
