using System.Collections.ObjectModel;
using System.Windows.Input;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using AnnoDesigner.Core.Models;
using AnnoDesigner.Models;
using AnnoDesigner.Models.Interface;

namespace AnnoDesigner.ViewModels
{
    public partial class WelcomeViewModel : ObservableObject
    {
        private readonly ICommons _commons;
        private readonly IAppSettings _appSettings;

        [ObservableProperty]
        private ObservableCollection<SupportedLanguage> _languages = new();

        [ObservableProperty]
        private SupportedLanguage _selectedItem;

        public WelcomeViewModel(ICommons commonsToUse, IAppSettings appSettingsToUse)
        {
            _commons = commonsToUse;
            _appSettings = appSettingsToUse;

            Languages =
            [
                new("English")
                {
                    FlagPath = "/Assets/Flags/United Kingdom.png"
                },
                new("Deutsch")
                {
                    FlagPath = "/Assets/Flags/Germany.png"
                },
                new("Français")
                {
                    FlagPath = "/Assets/Flags/France.png"
                },
                new("Polski")
                {
                    FlagPath = "/Assets/Flags/Poland.png"
                },
                new("Русский")
                {
                    FlagPath = "/Assets/Flags/Russia.png"
                },
                new("Español")
                {
                    FlagPath = "/Assets/Flags/Spain.png"
                },
            ];

            // ContinueCommand is generated via the [RelayCommand] attribute on the Continue method below.
        }

        // Languages and SelectedItem backing fields are generated by [ObservableProperty]

        [RelayCommand(CanExecute = nameof(CanContinue))]
        private void Continue(object? param)
        {
            LoadSelectedLanguage(param as ICloseable);
        }

        private bool CanContinue(object? param)
        {
            return SelectedItem != null;
        }

        private void LoadSelectedLanguage(ICloseable window)
        {
            _commons.CurrentLanguage = SelectedItem.Name;

            _appSettings.SelectedLanguage = _commons.CurrentLanguage;
            _appSettings.Save();

            window?.Close();
        }
    }
}
